### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by icancclearynow** [icancclearynow/nuxtjs-contentful-blog#329]
https://github.com/nuxt-community/color-mode-module

**Comment by iancleary** [comment]
Find out if there is a way that elementary OS detects dark style preference

**Comment by iancleary** [comment]
Do I really need this? Probably not

**Comment by iancleary** [comment]
So the firefox flatpak doesn't seem to have a portal for this.  elementary web works and detects it with https://color-mode.nuxtjs.org/, which (as of this writing) Firefox doesn't

https://color-mode.nuxtjs.org/
